{"name": "test_negative_create_new_task[invalid_data2-401-You do not have access to this task-ACCESS_083]", "status": "passed", "description": "Create task with wrong name, parent ID, link ID and validate that errors are equal to expected", "steps": [{"name": "Create new task with body: {'name': 'whatever', 'links_to': 935}, expected status code: 401", "status": "passed", "steps": [{"name": "Create url with base url and endpoint: /list/901510919856/task\nResult URL: https://api.clickup.com/api/v2/list/901510919856/task", "status": "passed", "start": 1746889610082, "stop": 1746889610082}, {"name": "Send POST request to https://api.clickup.com/api/v2/list/901510919856/task with json={'name': 'whatever', 'links_to': 935} and data=None, expected status code 401", "status": "passed", "start": 1746889610082, "stop": 1746889610593}], "start": 1746889610082, "stop": 1746889610593}], "parameters": [{"name": "invalid_data", "value": "{'name': 'whatever', 'links_to': 935}"}, {"name": "expected_status_code", "value": "401"}, {"name": "expected_err_message", "value": "'You do not have access to this task'"}, {"name": "expected_err_code", "value": "'ACCESS_083'"}], "start": 1746889610082, "stop": 1746889610593, "uuid": "97d288a9-ffd2-405c-80a3-5e3a3802b471", "historyId": "a6c5e73ba5ea26d62ae18d99228037b8", "testCaseId": "2b634744f349a3d06f3aee13d601988d", "fullName": "tests.api.test_tasks.TestTasks#test_negative_create_new_task", "labels": [{"name": "feature", "value": "Manage tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "apachai"}, {"name": "thread", "value": "11548-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}