{"name": "test_negative_create_new_task[invalid_data2-401-You do not have access to this task-ACCESS_083]", "status": "passed", "description": "Create task with wrong name, parent ID, link ID and validate that errors are equal to expected", "steps": [{"name": "Create new task with body: {'name': 'bank', 'links_to': 409}, expected status code: 401", "status": "passed", "steps": [{"name": "Create url with base url and endpoint: /list/901510919856/task\nResult URL: https://api.clickup.com/api/v2/list/901510919856/task", "status": "passed", "start": 1746874170130, "stop": 1746874170130}, {"name": "Send POST request to https://api.clickup.com/api/v2/list/901510919856/task with json={'name': 'bank', 'links_to': 409} and data=None, expected status code 401", "status": "passed", "start": 1746874170130, "stop": 1746874170678}], "start": 1746874170130, "stop": 1746874170678}], "parameters": [{"name": "invalid_data", "value": "{'name': 'bank', 'links_to': 409}"}, {"name": "expected_status_code", "value": "401"}, {"name": "expected_err_message", "value": "'You do not have access to this task'"}, {"name": "expected_err_code", "value": "'ACCESS_083'"}], "start": 1746874170130, "stop": 1746874170678, "uuid": "87897c59-e3c0-4a0b-ab55-9ac1a1e7bf71", "historyId": "3f14dcd8880c87e33c3b1d08ca00c7d5", "testCaseId": "2b634744f349a3d06f3aee13d601988d", "fullName": "tests.api.test_tasks.TestTasks#test_negative_create_new_task", "labels": [{"name": "feature", "value": "Manage tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "apachai"}, {"name": "thread", "value": "28204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}