{"name": "test_negative_create_new_task[invalid_data2-401-You do not have access to this task-ACCESS_083]", "status": "passed", "description": "Create task with wrong name, parent ID, link ID and validate that errors are equal to expected", "steps": [{"name": "Create new task with body: {'name': 'account', 'links_to': 180}, expected status code: 401", "status": "passed", "steps": [{"name": "Create url with base url and endpoint: /list/901510919856/task\nResult URL: https://api.clickup.com/api/v2/list/901510919856/task", "status": "passed", "start": 1746888820908, "stop": 1746888820908}, {"name": "Send POST request to https://api.clickup.com/api/v2/list/901510919856/task with json={'name': 'account', 'links_to': 180} and data=None, expected status code 401", "status": "passed", "start": 1746888820908, "stop": 1746888821436}], "start": 1746888820908, "stop": 1746888821436}], "parameters": [{"name": "invalid_data", "value": "{'name': 'account', 'links_to': 180}"}, {"name": "expected_status_code", "value": "401"}, {"name": "expected_err_message", "value": "'You do not have access to this task'"}, {"name": "expected_err_code", "value": "'ACCESS_083'"}], "start": 1746888820908, "stop": 1746888821436, "uuid": "55b85b16-02fd-4f28-9222-8f216fc7f631", "historyId": "23a4d6d4d19447740e4533f6fdf36c32", "testCaseId": "2b634744f349a3d06f3aee13d601988d", "fullName": "tests.api.test_tasks.TestTasks#test_negative_create_new_task", "labels": [{"name": "feature", "value": "Manage tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "apachai"}, {"name": "thread", "value": "18260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}